sudo: required
services:
  - docker

before_install:
  - docker build -t vpelagatti/docker-react -f Dockerfile.dev .

script:
  - docker run vpelagatti/docker-react CI=true npm run test -- --coverage
