services:
  - docker

before_install:
  - docker build -t vpelagatti/docker-react -f Dockerfile.dev .

install: travis_wait mvn install

script:
  - docker run vpelagatti/docker-react npm run test -- --coverage
