install: travis_wait 30 mvn install

services:
  - docker

before_install:
  - docker build -t vpelagatti/docker-react -f Dockerfile.dev .

script:
  - docker run vpelagatti/docker-react npm run test -- --coverage
